project_id = "ywwlxczxktoqhjehitds"

[functions.parse-tasks]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = true

[functions.microsoft-calendar-sync]
verify_jwt = true

[functions.ai-suggest-tasks]
verify_jwt = false

[functions.analyze-availability]
verify_jwt = true

[functions.schedule-tasks]
verify_jwt = true
